[package]
name = "libjuice-sys"
version = "0.9.7"
edition = "2021"
description = "Native bindings for libjuice"
license = "LGPL-2.1"
homepage = "https://github.com/VollmondT/juice-rs"
authors = ["Vyacheslav S. Troshin"]

[build-dependencies]
bindgen = "0.59"
cmake = "0.1"
